"""empty message

Revision ID: f44c0651e19b
Revises: 3eeb0cf76dfb
Create Date: 2021-10-28 02:13:29.817420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44c0651e19b'
down_revision = '3eeb0cf76dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course', sa.Column('preview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Course', 'preview')
    # ### end Alembic commands ###
